name: CI/CD - Hola Python Railway

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: 📥 Clonar el repositorio
      uses: actions/checkout@v3

    - name: 🐍 Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: 📦 Instalar dependencias
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: 🐳 Iniciar sesión en DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: 🏗️ Construir imagen Docker
      run: |
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/hola-py .

    - name: 🏷️ Etiquetar imagen
      run: |
        docker tag ${{ secrets.DOCKERHUB_USERNAME }}/hola-py ${{ secrets.DOCKERHUB_USERNAME }}/hola-py:latest

    - name: 📤 Subir imagen a DockerHub
      run: |
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/hola-py:latest
